version: "3.8"

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    hostname: portainer

    user: root
    networks:
      - monitoreo_cosas
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
networks:
  monitoreo_cosas:
