version: '3.8'

services:
  nginx-test:
    container_name: firmware-nginx
    image: nginx
    ports:
      - 9191:80
    volumes:
      - ./nginx-conf:/etc/nginx
      - ./data:/var/www/updateserver
    privileged: true
    networks:
      monitoreo_cosas:
        ipv4_address: 172.23.0.41
networks:
  monitoreo_cosas:
    external: true
