version: "3.7"
services:
  cloudflare-ddns:
    image: joshava/cloudflare-ddns:arm32v6
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - CRON=0 */12 * * *
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: always
