version: "3.8"

services:
  sonar:
    image: sonarqube-custom:v10
    container_name: sonarqube-app
    privileged: true
    ports:
      - '9091:9000'
    stdin_open: true 
    networks:
      - monitoreo_cosas
    tty: true
    volumes:
      - ./sonarqube_data/data/plugins:/opt/sonarqube/extensions/plugins

networks:
  monitoreo_cosas:
    external: true