version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    networks:
      monitoreo_cosas:
        ipv4_address: 172.23.0.32
    ports:
      - "192.168.0.240:53:53/tcp"
      - "192.168.0.240:53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "1010:80/tcp"
    environment:
      TZ: 'America/Argentina/Cordoba'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped

networks:
  monitoreo_cosas:
    external: true
