version: "3.8"
services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    environment:
      - .env
    networks:
      monitoreo_cosas:
        ipv4_address: 172.23.0.36

networks:
  monitoreo_cosas:
    external: true
volumes:
  influxData:
